var Operation = require('./operation.js')
  , xmlbuilder = require('xmlbuilder')

function Service(id, opts) {
  this.id = id
  this.operations = {}
  this.url = null
  this.device = opts.device
}


Service.prototype.createOperation = function (operationId, opts) {
  return this.operations[operationId] = new Operation(operationId, opts)
}

Service.prototype.wsdl = function () {
  var xml = xmlbuilder
    .create('s12:Envelope', { encoding: 'UTF-8', version: '1.0' })
    .att('xmlns:dpws', 'http://docs.oasis-open.org/ws-dd/ns/dpws/2009/01')
    .att('xmlns:s12', 'http://www.w3.org/2003/05/soap-envelope')
    .att('xmlns:wsa', 'http://www.w3.org/2005/08/addressing')
    .att('xmlns:wsx', 'http://schemas.xmlsoap.org/ws/2004/09/mex')
    .e('s12:Header')
      .e('wsa:Action', 'http://schemas.xmlsoap.org/ws/2004/09/mex/GetMetadata/Response').up()
      .e('wsa:RelatesTo', 'urn:uuid:7d333fc0-4def-11e3-bf4e-39ab02163fe9').up()
      .e('wsa:To', 'http://www.w3.org/2005/08/addressing/anonymous').up()
    .up()
    .e('s12:Body')
      .e('wsx:Metadata')
        .e('wsx:MetadataSection')
        .att('Dialect', 'http://schemas.xmlsoap.org/wsdl/')
          .e('wsdl:definitions')
          .att('xmlns:wsdl', 'http://schemas.xmlsoap.org/wsdl/')
          .att('xmlns:dpws', 'http://docs.oasis-open.org/ws-dd/ns/dpws/2009/01')
          .att('xmlns:wsoap12', 'http://schemas.xmlsoap.org/wsdl/soap12/')
          .att('xmlns:xs', 'http://www.w3.org/2001/XMLSchema')
            .e('wsdl:types')
              .e('xs:schema')
              .att('xmlns:xsi', 'http://www.w3.org/2001/XMLSchema-instance')
              .att('elementFormDefault', 'qualified')
              .att('attributeFormDefault', 'unqualified')
                .e('xs:element')
                .att('name', 'Temperature')
                .att('type', 'xs:int')
                .up()
              .up()
            .up()
            .e('wsdl:message').att('name', 'GetStatusMessage').up()
            .e('wsdl:message')
            .att('name', 'GetStatusResponseMessage')
              .e('wsdl:part')
              .att('name', 'parameters')
              .att('element', 'tns:Temperature')
              .up()
            .up()
            .e('wsdl:portType')
            .att('name', 'AC_serviceInterface')
              .e('wsdl:operation')
              .att('name', 'GetStatus')
                .e('wsdl:input')
                .att('name', 'GetStatus')
                .att('message', 'tns:GetStatusMessage')
                .att('wsa:Action', 'http://www.csd.uoc.gr/~sultatos/AC_serviceInterface/GetStatus')
                .up()
                .e('wsdl:output')
                .att('name', 'GetStatusResponse')
                .att('message', 'tns:GetStatusResponseMessage')
                .att('wsa:Action', 'http://www.csd.uoc.gr/~sultatos/AC_serviceInterface/GetStatusResponse')
                .up()
              .up()
            .up()
            .e('wsdl:binding')
            .att('name', 'ACServiceSoapBinding')
            .att('type', 'tns:AC_serviceInterface')
              .e('wsoap12:binding')
              .att('style', 'document')
              .att('transport', 'http://schemas.xmlsoap.org/soap/http')
              .up()
              .e('wsdl:operation')
              .att('name', 'GetStatus')
                .e('wsoap12:operation').up()
                .e('wsdl:input')
                  .e('wsoap12:body').att('use', 'literal').up()
                .up()
                .e('wsdl:output')
                  .e('wsoap12:body').att('use', 'literal').up()
                .up()
              .up()
              .e('wsdl:service')
              .att('name', this.id)
                .e('wsdl:port')
                .att('name', 'ACPort')
                .att('binding', 'tns:ACServiceSoapBinding')
                  .e('wsoap12:address')
                  .att('location', this.url)
                  .up()
                .up()
              .up()
            .up()
          .up()
        .up()
        .e('wsx:MetadataSection')
        .att('Dialect', 'http://docs.oasis-open.org/ws-dd/ns/dpws/2009/01/Relationship')
          .e('dpws:Relationship')
          .att('Type', 'http://docs.oasis-open.org/ws-dd/ns/dpws/2009/01/host')
            .e('dpws:Host')
              .e('wsa:EndpointReference')
                .e('wsa:Address', this.device.address).up()
              .up()
              .e('dpws:Types', this.device.types).up()
            .up()
            .e('dpws:Hosted')
            .e('wsa:EndpointReference')
              .e('wsa:Address', this.url).up()
            .up()
            .e('dpws:Types', this.device.types).up()
            .e('dpws:ServiceId', this.id).up()
          .up()
        .up()
      .up()
        

  return xml.end({ pretty: true })
}

module.exports = Service
